# Adapted from https://github.com/doctea/usb_midi_clocker/blob/main/add_git_branch.py
# 2024-02-03 
import datetime

import subprocess

def make_version_header():
    # dont track changes to the output file
    subprocess.run(["git", "update-index", "--skip-worktree", "build_info_env.ini"])

    # fetch branch info from git
    ret = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], stdout=subprocess.PIPE, text=True)
    build_version = ret.stdout.strip()
    ret = subprocess.run(["git", "rev-parse", "--short", "HEAD"], stdout=subprocess.PIPE, text=True)
    build_version += " "
    build_version += ret.stdout.strip()

    ret = subprocess.run(["git", "diff", "HEAD"], stdout=subprocess.PIPE, text=True)
    status = " clean" if ret.stdout.strip()=="" else " (dirty)"
    build_version += status

    print ("build_version = " + build_version)

    # write to file
    f = open("build_info_env.ini","w")
    f.write("# do not edit this file - automatically generated during build\n")
    f.write("# regenerated at %s\n\n" % datetime.datetime.now())
    f.write("[build_info]\ncommit_info=\"" + build_version + "\"\n\n")
    f.close()

make_version_header()